-- ============================================
-- USER SESSIONS / DEVICE LIMIT
-- ============================================

CREATE TABLE IF NOT EXISTS user_sessions (

  id bigint generated always as identity primary key,

  user_id uuid not null
    REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Random identifier generated by the QuizStep browser.
  -- Used internally to identify a browser installation.
  device_id text not null,

  -- Human-readable information for the user.
  device_name text,

  -- Simple category: phone / tablet / desktop / unknown.
  device_type text NOT NULL DEFAULT 'unknown'
    CHECK (device_type IN ('phone', 'tablet', 'desktop', 'unknown')),

  -- Browser used to create the session (e.g. Chrome, Edge, Brave).
  browser_name text,

  created_at timestamptz NOT NULL DEFAULT now(),

  last_active_at timestamptz NOT NULL DEFAULT now(),

  -- Session automatically stops counting after this time.
  expires_at timestamptz NOT NULL,

  -- NULL = not manually revoked.
  revoked_at timestamptz
);


-- ============================================
-- INDEXES
-- ============================================

-- Prevent the same user/device combination from having
-- multiple active sessions.
CREATE UNIQUE INDEX IF NOT EXISTS user_sessions_active_device_unique
ON user_sessions (user_id, device_id)
WHERE revoked_at IS NULL;


-- Makes active-device lookups efficient.
CREATE INDEX IF NOT EXISTS user_sessions_active_lookup
ON user_sessions (user_id, expires_at)
WHERE revoked_at IS NULL;


-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;


-- Users can view their own sessions.
CREATE POLICY "Users can view own sessions"
ON user_sessions
FOR SELECT
USING (auth.uid() = user_id);


-- Users can revoke their own sessions.
-- The WITH CHECK ensures revoked_at must be set to a non-null
-- value upon update (sessions can only be revoked, not un-revoked).
CREATE POLICY "Users can revoke own sessions"
ON user_sessions
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (
  auth.uid() = user_id
  AND revoked_at IS NOT NULL
);


-- ============================================
-- REALTIME CONFIGURATION
-- ============================================
-- Allows Supabase Realtime to broadcast row updates
-- so revoked devices get kicked out instantly without refresh.

ALTER TABLE user_sessions REPLICA IDENTITY FULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'user_sessions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE user_sessions;
  END IF;
END $$;